logging:
  level:
    root: info

app:
  env: "${ENVIRONMENT:local}"

spring:

  kafka:
    bootstrap-servers: 127.0.0.1:9092
  cloud:
    stream:
      bindings:
        registerVote-out-0:
          destination: ${app.env}.votes
    function:
      definition: registerVote

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stave_db
    username: postgres
    password: stave_password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090

schedule-verification-votes: "0/30 * * ? * *"

integrations:
  validate-document:
    url: "https://user-info.herokuapp.com"
    enabled: ${DOCUMENT_VALIDATION_ACTIVE:true}
